### PR TITLE
Update route.md: fix link

### PR DESCRIPTION
**Pull request by axelsimon**
Hope this helps :)

### CODE REVIEW

**Comment by francislavoie** [comment]
Hmm, this doesn't seem right. "re-ordered" is not a directive or other kind of code related thing, so wrapping it in backticks to use `<code>` around it doesn't make sense.

**Comment by francislavoie** [comment]
This made me dig deeper to see what's going on, I think the problem is that caddyserver.com is running a build of Caddy which was missing some fixes in the Markdown parser https://github.com/yuin/goldmark which made that link parse incorrectly (I'm guessing because it was preceded by `2)` on the same line which made it incorrectly parse the link which also contains `)` characters).

I'm asking @mholt to update the site with a fixed version.

**Comment by mholt** [comment]
Phew, finally fixed. The site's now running the latest commits of Caddy, and Caddy v2.5 will have the fix.

**Comment by axelsimon** [comment]
Ok, good to hear this eventually helped uncover something!

**Pull request closed without merging**
