### PR TITLE
docs: Caddy is also available on Termux

### PR DESCRIPTION
**Pull request by thunder-coding**

### CODE REVIEW

**Comment by francislavoie** [comment]
Could you add a link to somewhere that shows where this comes from? Is there a manifest online somewhere, or is it in a git repo?

**Comment by thunder-coding** [comment]
About Termux: https://wiki.termux.com/wiki/Main_Page

The Termux packages repository: https://github.com/termux/termux-packages

**Comment by finagolfin** [comment]
I am a termux package maintainer: we don't have individual package webpages or manifests. [The shell script for this package that integrates with our build system is here](https://github.com/termux/termux-packages/blob/master/packages/caddy/build.sh).

**Comment by thunder-coding** [comment]
Ping: Isn't this PR ready to merge?

**Comment by francislavoie** [comment]
Like I said, I'd like a link to the build script to be added to this section, similar to Scoop and the community maintained installation methods, for consistency.

**Comment by thunder-coding** [comment]
> Like I said, I'd like a link to the build script to be added to this section, similar to Scoop and the community maintained installation methods, for consistency.

Done ✅

**Review by francislavoie — APPROVED** [review]

**Pull request merged**
