### PR TITLE
Better styles and ux

### PR DESCRIPTION
**Pull request by AmagiDDmxh**
1. Add .current class to the current link
2. sticky sidebar

### CODE REVIEW

**Comment by francislavoie** [comment]
> Add .current class to the current link

It already does this. I don't understand what you're trying to fix.

> sticky sidebar

I'm not sure I like this, because it adds a scroll bar to the sidebar.

Either way, @mholt is working on a redesign, so these changes will effectively be thrown away soon once that's completed.

**Comment by mholt** [comment]
Yeah; I agree, I'm not quite sure what the problem is.

**Comment by AmagiDDmxh** [comment]
> It already does this. I don't understand what you're trying to fix.

There were two implementations of **.current class active** in `src/resources/js/docs.js` and in `src/resources/js/account/common.js`. However, none of them are working as expected.

The sticky sidebar can be deleted. 

Thank you very much for mentioning the redesign. So this could be a closed pr.

**Comment by francislavoie** [comment]
> However, none of them are working as expected.

I don't agree? It works fine. Notice `Directives` is highlighted as the current page.

**Comment by AmagiDDmxh** [comment]
> > However, none of them are working as expected.
> 
> I don't agree? It works fine. Notice `Directives` is highlighted as the current page.
> 
> 

But it didn't work on header-nav

Before at /docs page

CleanShot 2023-08-12 at 17 47 22

After

CleanShot 2023-08-12 at 17 48 03

**Pull request closed without merging**
