### PR TITLE
docs: Clarify log roll_keep_for parameter

### PR DESCRIPTION
**Pull request by francislavoie**
As per https://caddy.community/t/somes-issues-from-the-docs/7567/2

### CODE REVIEW

**Comment by francislavoie** [comment]
Looks like this is wrong - Hmm.

**Comment by mholt** [comment]
I think this is correct though. what's wrong with it? 🧐

**Comment by francislavoie** [comment]
The problem is that the docs didn't specify a working value. Turns out it's not just an `int` either, it needs to be a duration, but the duration type doesn't handle number of days, so it needs to be specified in hours. I'll fix it in a sec

**Review by mholt — APPROVED** [review]
Oh -- thanks. This reminds me I want to write a duration parser that accepts day units :P

**Pull request merged**
