### PR TITLE
Clarify that the JSON doc is the doc for matchers

### PR DESCRIPTION
**Pull request by mbernasocchi**
this adresses https://github.com/caddyserver/caddy/issues/3041

### CODE REVIEW

**Comment by francislavoie** [comment]
That's not exactly true, the Caddyfile matcher docs are directly below the part you edited.

See the block after `The following matcher modules are built-in:`

**Comment by francislavoie** [comment]
FWIW I think Caddyfile matchers should have their own page @mholt, considering how important it is

**Comment by mbernasocchi** [comment]
> That's not exactly true, the Caddyfile matcher docs are directly below the part you edited.
> 
> See the block after `The following matcher modules are built-in:`

Yes I saw that, but that par is super "skinny" where the JSON doc is so much better. Keep in mind that I started using caddy today, so I've got the "perfect noob coming from nginx" perspective :smile:

**Comment by mholt** [comment]
Yeah... and, well, there's a difference between _what a matcher is_ and _which matchers are available_.

I agree we should put which matchers are available on a separate page. In the long run, I also want better inter-linking between the JSON <--> Caddyfile equivalent docs. So I'll close this PR.

**Comment by mholt** [comment]
@mbernasocchi 

> Keep in mind that I started using caddy today, so I've got the "perfect noob coming from nginx" perspective 😄

Great, welcome! Have you seen our WIP [nginx adapter](https://github.com/caddyserver/nginx-adapter)? It lets you run Caddy from an NGINX config (mostly).

**Comment by mbernasocchi** [comment]
not yet, but I'd like to learn caddy to go away from nginx files ;)

**Pull request closed without merging**
