### PR TITLE
Implement light/dark theme toggle, docsearch dark theme

### PR DESCRIPTION
**Pull request by francislavoie**
Uses https://github.com/GoogleChromeLabs/dark-mode-toggle as the widget

It displays right under the sidebar docs nav, couldn't really find a better place to put it on short notice.

Moved the dark theme into a separate file as recommended by the lib, uses the `media="(prefers-color-scheme: dark)"` selector on the `<link>` instead of inside the CSS file, which makes the CSS conditionally load instead of always loading but only sometimes being enabled.

I pulled in the unpkg.com CDN version of the lib, hopefully you don't mind that. Didn't want to use npm for this. It's a widget by Google, I think it might only work in modern browsers that support `type="module"`, in other words not IE11, not UC Browser (china/india). Probably not an issue.

image

Edit: Also adds dark styles for the docsearch input and dropdown

image

### CODE REVIEW

**Comment by francislavoie** [comment]
Ah crap I noticed a couple issues, hold on...

**Comment by francislavoie** [comment]
Alright well there's some flicker if you have system dark turned on but choose light theme, when a new page loads or you refresh. Doesn't always happen though, depends on how the browser ends up painting the site.

Opened an issue to see if anyone has any tips https://github.com/GoogleChromeLabs/dark-mode-toggle/issues/25

Should still be good enough though, better than having no toggle at all!

**Comment by francislavoie** [comment]
Added the docsearch dark theme into this PR, because this PR also moves the dark themes to another file, so I would've had to make a branch off of this branch etc. Easier to just put it in the same PR.

**Comment by francislavoie** [comment]
@mholt I rebased and updated the styles to match your changes 👍

**Comment by mholt** [comment]
Wow, that commit sha tho: 55555db

Thanks Francis! I'll look at this shortly :+1:

**Comment by mholt** [comment]
K, I pulled this down and it looks pretty good! A few things:

- Code blocks don't get proper dark theme when I select Dark but when my system theme switches to Dark, it does.
- How hard would it be to add a toggle to use the system theme? It's confusing for me since my theme changes automatically at day and night. I think I would like to know whether my preference is overriding the system theme or if I'm using it.

Thanks for working on this!

**Comment by francislavoie** [comment]
> How hard would it be to add a toggle to use the system theme? It's confusing for me since my theme changes automatically at day and night. I think I would like to know whether my preference is overriding the system theme or if I'm using it.

Oh, good point. I don't think the lib we're using now supports that out of the box. I think it uses local storage though, we could add our own button to wipe the setting, but I'm not sure adding a 3rd button is ideal.

> Code blocks don't get proper dark theme when I select Dark but when my system theme switches to Dark, it does.

I think all we need to do to fix that is to make a new file `chroma-dark.css` similarly to the other one. Seem okay?

Edit: made that change

**Comment by francislavoie** [comment]
Ah, looks like the lib sets the property in local storage to your system preference on page load. I think this approach will just always break dynamic system theme changes.

**Comment by mholt** [comment]
To clarify, I think we need a 3-way toggle: Light, Dark, and System. Right now there's no way for me to switch back to using the system theme.

I'm still seeing confusing behavior when I switch my system theme or use my system's Auto theme. Do you have a Mac you can test with?

The code blocks look better though!

**Comment by francislavoie** [comment]
That's what the JS code I added handles, if the system preference changes, it will unset the saves theme. I don't have a way to unset with a button, but any system change should reset it. I don't have a Mac, no.

**Review by mholt — CHANGES_REQUESTED** [review]
Thanks for working on this. I've been using this some more and like it, but it really needs a way to reset to the default, which is the system theme (i.e. a third toggle) -- over a couple days I got confused why the theme wasn't changing or how to change it back to the default, because I end up having to go into the system preferences to change how a website looks!

But, other than that, it's looking good!

**Comment by francislavoie** [comment]
I don't understand why that would be happening, why's the JS I added not working for you? What's different about how macOS is setting the preferred color scheme?

To be clear, there's no such thing as "system theme" in `prefers-color-scheme`: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme there's only "light", "dark", and "no-preference".

**Comment by mholt** [comment]
I'm not sure what's going on either, but at least a way to switch back to "no preference" I assume is what we need. Edit: Actually, maybe that's not quite accurate -- what I mean is that we need a toggle on the web page to switch back to whichever theme the system prefers, rather than forcing light or dark.

For example, Sourcegraph has a 3-way toggle: 
Screen Shot 2020-04-06 at 3 18 02 PM

**Comment by francislavoie** [comment]
Well here's how you can debug - open the Storage tab in your browser, and choose "Local Storage". You'll be able to see the key-val pairs that are set.

Otherwise, it'll require using a totally different lib because this one just grabs the system setting and stores it to the `dark-mode-toggle` local storage key on page load if no value is set.

**Comment by mholt** [comment]
Francis, to be clear, the issue is the lack of a third option: to use the system theme.

**Comment by francislavoie** [comment]
What I'm trying to explain is that I don't think that'll solve anything. If your system theme is set to "light", just click the "light" button and it'll be re-synced with the system theme, then the next time the OS automatically changes the theme at sunset or whatever, the JS code I wrote will wipe the `dark-mode-toggle` storage key so that it changes to "dark" correctly.

**Comment by mholt** [comment]
It's not a matter of getting the colors right, it's a matter of knowing what my preference is set to. If there is a default (and there is), I need to be able to unset my config. That's not clear right now with just two options. There has to be a third.

**Comment by francislavoie** [comment]
What I'm saying is that that's not something https://github.com/GoogleChromeLabs/dark-mode-toggle supports, because there's no such thing as "default" in `prefers-color-scheme`. If we unset `dark-mode-toggle`, it sets itself again next time you load the page, to either "light" or "dark".

**Comment by mholt** [comment]
That's a bummer. I think we'll need that before I'm willing to admit the change. Maybe we can see how Sourcegraph is doing it.

**Comment by francislavoie** [comment]
I opened https://sourcegraph.com/github.com/caddyserver/caddy/-/blob/modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go#L217:24 and I don't see anywhere to change the theme, not sure where you found that toggle

**Comment by mholt** [comment]
Weird, it shows up for me. 🤷‍♂ Top-right corner, in a dropdown.

**Comment by francislavoie** [comment]
I got nothing. Edit: Apparently you need to be logged in to get the toggle... weird.

image

But seriously, I don't understand the issue. When is it not in sync with the system? Why can't you just click "light" during the day or "dark" at night to resync it? It should stay in sync if you set it to the same as system.

**Comment by mholt** [comment]
Closing due to inactivity

**Comment by mholt** [comment]
Here's one possibility, though it uses React (would need to be vanilla JS or jQuery) : https://twitter.com/silvenon/status/1421890589432422414

**Pull request closed without merging**
