### PR TITLE
chore: Add .editorconfig

### PR DESCRIPTION
**Pull request by francislavoie**

### CODE REVIEW

**Comment by mholt** [comment]
What is this?

**Comment by francislavoie** [comment]
https://editorconfig.org/

Most editors/IDEs (including VSCode) support reading from this file automatically to set defaults for file types

Edit: I guess VSCode doesn't have it by default :man_facepalming: but you can just install this https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig

**Comment by mholt** [comment]
Do any of the maintainers use anything other than VS Code? If we have to opt-in anyway I'm not sure that putting this in the repo does any good.

**Comment by francislavoie** [comment]
It's pretty standard to include it in repos, frankly. It's a declaration of what kind of indentation style you want in that repo. I see no harm in including it, even if it's not enabled for everyone. It'll solve the issue for me, and likely whoever else contributes (who also use an IDE that support it - which is most)

**Review by mholt — APPROVED** [review]
Okie, thanks!

**Pull request merged**
