### PR TITLE
docs: Remove NTLM transport from the docs now that it's a separate module

### PR DESCRIPTION
**Pull request by francislavoie**

### CODE REVIEW

**Review by mholt — CHANGES_REQUESTED** [review]
Actually we should probably remove the docs for the NTLM transport entirely.

**Comment by francislavoie** [comment]
Ok - do you have plans to document "official" non-core plugins somewhere in the site?

**Comment by mholt** [comment]
Yeah, after 2.0 is released I'll spend some time on the website so that people can register their third-party plugins just like with v1 (but way better this time I hope).

**Review by mholt — APPROVED** [review]
Awesome, thank you!

**Comment by mholt** [comment]
I appreciate the help staying on top of the docs 😅

**Pull request merged**
